# Generated by Django 5.2.8 on 2025-12-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_fields_to_groom_bride_and_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridesocialmedia',
            name='bride',
        ),
        migrations.RemoveField(
            model_name='giftaddress',
            name='client',
        ),
        migrations.RemoveField(
            model_name='giftbankinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='groomparents',
            name='groom',
        ),
        migrations.RemoveField(
            model_name='groomsocialmedia',
            name='groom',
        ),
        migrations.RemoveField(
            model_name='unduhmantuevent',
            name='client',
        ),
        migrations.RemoveField(
            model_name='videogallery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='formal_photo',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='brideinfo',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='education',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='formal_photo',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='groominfo',
            name='short_description',
        ),
        # Note: father_name and mother_name already added in migration 0002
        migrations.AlterField(
            model_name='brideinfo',
            name='child_order',
            field=models.CharField(blank=True, help_text='Contoh: Putri pertama dari', max_length=100, verbose_name='Putra/Putri Ke-'),
        ),
        migrations.AlterField(
            model_name='brideinfo',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bride_photos/', verbose_name='Foto Utama'),
        ),
        migrations.AlterField(
            model_name='brideinfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Panggilan'),
        ),
        migrations.AlterField(
            model_name='groominfo',
            name='child_order',
            field=models.CharField(blank=True, help_text='Contoh: Putra pertama dari', max_length=100, verbose_name='Putra/Putri Ke-'),
        ),
        migrations.AlterField(
            model_name='groominfo',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='groom_photos/', verbose_name='Foto Utama'),
        ),
        migrations.AlterField(
            model_name='groominfo',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Panggilan'),
        ),
        migrations.AlterField(
            model_name='receptionevent',
            name='adab_walimah',
            field=models.TextField(blank=True, help_text='Panduan adab untuk tamu undangan', verbose_name='Adab Walimah'),
        ),
        migrations.DeleteModel(
            name='BrideParents',
        ),
        migrations.DeleteModel(
            name='BrideSocialMedia',
        ),
        migrations.DeleteModel(
            name='GiftAddress',
        ),
        migrations.DeleteModel(
            name='GiftBankInfo',
        ),
        migrations.DeleteModel(
            name='GroomParents',
        ),
        migrations.DeleteModel(
            name='GroomSocialMedia',
        ),
        migrations.DeleteModel(
            name='UnduhMantuEvent',
        ),
        migrations.DeleteModel(
            name='VideoGallery',
        ),
    ]
