# Generated by Django 5.2.8 on 2025-12-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_bridesocialmedia_bride_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brideinfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Ayah'),
        ),
        migrations.AddField(
            model_name='brideinfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Ibu'),
        ),
        migrations.AddField(
            model_name='groominfo',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Ayah'),
        ),
        migrations.AddField(
            model_name='groominfo',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Ibu'),
        ),
    ]
