# Generated by Django 5.2.8 on 2025-12-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0005_delete_backgroundasset_and_more'),
        ('users', '0004_brideinfo_father_name_brideinfo_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='selected_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation_templates.theme', verbose_name='Tema Terpilih'),
        ),
    ]
