# Generated by Django 5.2.8 on 2025-12-16 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0005_delete_backgroundasset_and_more'),
        ('users', '0005_clientprofile_selected_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_slug', models.SlugField(help_text='URL unik untuk undangan (contoh: romeo-juliet)', max_length=200, unique=True, verbose_name='Slug Undangan')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Aktif'), ('inactive', 'Nonaktif')], default='draft', max_length=20, verbose_name='Status')),
                ('is_public', models.BooleanField(default=True, help_text='Apakah undangan bisa diakses publik tanpa login', verbose_name='Publik')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terakhir Dilihat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='users.clientprofile', verbose_name='Klien')),
                ('theme', models.ForeignKey(blank=True, help_text='Tema yang dipilih untuk undangan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invitation_templates.theme', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Undangan',
                'verbose_name_plural': 'Undangan',
                'ordering': ['-created_at'],
            },
        ),
    ]
