# Generated by Django 5.2.8 on 2025-12-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Pengirim')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Alamat')),
                ('comment', models.TextField(verbose_name='Ucapan/Doa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wishes_images/', verbose_name='Gambar')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Disetujui')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim Pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='users.invitation', verbose_name='Undangan')),
            ],
            options={
                'verbose_name': 'Ucapan Undangan',
                'verbose_name_plural': 'Ucapan Undangan',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
