# Generated by Django 4.2.16 on 2025-12-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_invitationwish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='selected_theme',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='theme',
        ),
    ]
