# Generated by Django 5.2.8 on 2025-12-15 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor', 'timestamp'], name='admin_panel_actor_i_99ceab_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type', 'timestamp'], name='admin_panel_action__c660fa_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='admin_panel_target__e3cc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='admin_panel_recipie_9df588_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_type', 'priority'], name='admin_panel_notific_1a59b7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['broadcast_to_all_admins', 'is_read'], name='admin_panel_broadca_8da027_idx'),
        ),
    ]
