# Generated by Django 5.2.8 on 2025-12-15 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_activitylog_admin_panel_actor_i_99ceab_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Target Model'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Target Object ID'),
        ),
    ]
