# Generated by Django 5.2.8 on 2025-12-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_activitylog_target_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminnotification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='related_content_type',
        ),
        migrations.RemoveField(
            model_name='adminpreference',
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='SystemHealth',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs_as_target', to='contenttypes.contenttype', verbose_name='Target Model'),
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
        migrations.DeleteModel(
            name='AdminPreference',
        ),
    ]
