"""
Django settings for invywed project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f=#dj604d8^hipe-tlihphig1@&*d29_#xyv8cb#m2-x1rq1tb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django admin bawaan DIHAPUS - menggunakan custom admin panel saja
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'django_summernote',
    'fontawesomefree',
    'django_ace',
    
    # Local apps
    'core',
    'users',
    'admin_panel',
    'invitation_templates',
    'qr_manager',
    'thema',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF middleware DISABLED untuk development
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'invywed.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Arahkan ke folder templates di root project
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invywed.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Menggunakan PyMySQL untuk kompatibilitas dengan MariaDB 10.4 (XAMPP)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'undangan',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES', character_set_connection=utf8mb4, collation_connection=utf8mb4_unicode_ci",
            'charset': 'utf8mb4',
            'use_unicode': True,
            'connect_timeout': 10,
        },
        'CONN_MAX_AGE': 600,  # Connection pooling
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'id-id'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# X-Frame Options untuk Summernote
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Django Summernote Configuration
SUMMERNOTE_CONFIG = {
    'iframe': True,
    'summernote': {
        'airMode': False,
        'width': '100%',
        'height': '400',
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ]
    },
    'css': (
        '//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css',
    ),
    'js': (
        '//code.jquery.com/jquery-3.2.1.slim.min.js',
        '//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js',
    ),
    'attachment_upload_to': 'uploads/',
    'attachment_storage_class': 'django.core.files.storage.FileSystemStorage',
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''  # Isi dengan email Anda
EMAIL_HOST_PASSWORD = ''  # Isi dengan password/app password
DEFAULT_FROM_EMAIL = 'Invywed <noreply@invywed.com>'
SERVER_EMAIL = 'Invywed <noreply@invywed.com>'

# Session Configuration
SESSION_COOKIE_AGE = 86400  # 1 hari (dalam detik)
SESSION_COOKIE_SECURE = False  # Set True untuk HTTPS
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Configuration - DISABLED untuk development
CSRF_COOKIE_SECURE = False  # Set True untuk HTTPS
CSRF_COOKIE_HTTPONLY = False  # Disabled untuk development
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = []  # Tambahkan domain production nanti
# CSRF Protection disabled untuk development - AKTIFKAN LAGI SAAT PRODUCTION!
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = None  # Cookie tidak expire

# Security Settings (untuk production, uncomment dan sesuaikan)
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER = True

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB (100 * 1024 * 1024)
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB (100 * 1024 * 1024)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATA_UPLOAD_MAX_NUMBER_FILES = None  # Unlimited files

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Cache Configuration (optional - untuk production)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }

# Celery Configuration (optional - untuk background tasks)
# CELERY_BROKER_URL = 'redis://localhost:6379'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379'
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE

# Custom User Model (jika diperlukan)
# AUTH_USER_MODEL = 'users.CustomUser'

# Login/Logout URLs
# Authentication URLs
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/admin/'  # Redirect setelah login berhasil
LOGOUT_REDIRECT_URL = '/'

# Date/Time Format
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i'
TIME_FORMAT = 'H:i'
USE_L10N = True
USE_TZ = True

# Number Format
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'

# Admin Site Configuration
ADMIN_SITE_HEADER = "Invywed Administration"
ADMIN_SITE_TITLE = "Invywed Admin"
ADMIN_INDEX_TITLE = "Welcome to Invywed Administration"

# API Configuration (jika menggunakan REST API)
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 20,
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }

# WhatsApp API Configuration (untuk fitur broadcast)
WHATSAPP_API_URL = ''  # URL API WhatsApp Anda
WHATSAPP_API_KEY = ''  # API Key WhatsApp
WHATSAPP_PHONE_NUMBER = ''  # Nomor WhatsApp untuk API

# Payment Gateway Configuration (jika menggunakan payment gateway)
# MIDTRANS_SERVER_KEY = ''
# MIDTRANS_CLIENT_KEY = ''
# MIDTRANS_IS_PRODUCTION = False

# Google Maps API (untuk fitur maps)
GOOGLE_MAPS_API_KEY = ''  # API Key Google Maps

# Social Media Login (optional)
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ''
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ''
# SOCIAL_AUTH_FACEBOOK_KEY = ''
# SOCIAL_AUTH_FACEBOOK_SECRET = ''

# File Storage (untuk production, gunakan cloud storage)
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_ACCESS_KEY_ID = ''
# AWS_SECRET_ACCESS_KEY = ''
# AWS_STORAGE_BUCKET_NAME = ''
# AWS_S3_REGION_NAME = 'ap-southeast-1'

# Thumbnail Configuration
THUMBNAIL_DEBUG = DEBUG
THUMBNAIL_QUALITY = 85
THUMBNAIL_PRESERVE_EXTENSIONS = True

# Summernote Upload Settings
SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_UPLOAD_PATH = 'summernote_uploads/'
SUMMERNOTE_MAX_UPLOAD_SIZE = 5242880  # 5 MB

# FontAwesome Configuration
FONTAWESOME_CSS_URL = 'fontawesomefree/css/all.min.css'
FONTAWESOME_JS_URL = 'fontawesomefree/js/all.min.js'
