# Generated by Django 5.2.8 on 2025-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor WhatsApp')),
                ('name', models.CharField(max_length=100, verbose_name='Nama/Nickname')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Nomor Default')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='API Token (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Nomor WhatsApp',
                'verbose_name_plural': 'Nomor WhatsApp',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, verbose_name='Nama Template')),
                ('template_type', models.CharField(choices=[('inquiry', 'Pertanyaan'), ('order', 'Pemesanan'), ('complaint', 'Keluhan'), ('suggestion', 'Saran'), ('other', 'Lainnya')], max_length=20, verbose_name='Tipe Template')),
                ('message_content', models.TextField(verbose_name='Isi Pesan')),
                ('variables_info', models.TextField(blank=True, verbose_name='Info Variable ({nama}, {email}, dll)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template Default')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Penggunaan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Template WhatsApp User',
                'verbose_name_plural': 'Template WhatsApp User',
                'ordering': ['template_type', 'template_name'],
            },
        ),
    ]
