# Generated by Django 5.2.8 on 2025-12-19 03:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('icon_class', models.CharField(blank=True, max_length=50, verbose_name='CSS Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
            ],
            options={
                'verbose_name': 'Kategori Tema',
                'verbose_name_plural': 'Kategori Tema',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Tema')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('zip_file', models.FileField(help_text='Upload file ZIP yang berisi HTML, CSS, JS template', upload_to='themes/zip/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='File ZIP Template')),
                ('thumbnail', models.ImageField(blank=True, help_text='Gambar preview tema', null=True, upload_to='themes/thumbnails/', verbose_name='Thumbnail')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Tingkat Kesulitan')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Harga')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Download')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('extracted_path', models.CharField(blank=True, help_text='Path ke folder template yang sudah diextract', max_length=500, verbose_name='Path Template')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='thema.themecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Tema',
                'ordering': ['-created_at'],
            },
        ),
    ]
