# Generated by Django 5.2.8 on 2025-12-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='html_template',
        ),
        migrations.AddField(
            model_name='theme',
            name='html_file',
            field=models.FileField(blank=True, help_text='Upload file HTML untuk preview customer. File disimpan di folder templates_html/', null=True, upload_to='templates_html/', verbose_name='File HTML Template'),
        ),
    ]
