# Generated by Django 5.2.8 on 2025-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0002_remove_theme_html_template_theme_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='theme_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
