# Generated by Django 5.2.8 on 2025-12-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0003_alter_theme_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='html_file',
            field=models.CharField(blank=True, help_text='Nama file HTML template. File disimpan di folder templates_html/ di root project (bukan di media).', max_length=255, null=True, verbose_name='File HTML Template'),
        ),
    ]
