# Generated by Django 5.2.8 on 2025-12-16 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0004_alter_theme_html_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundAsset',
        ),
        migrations.AlterUniqueTogether(
            name='customcss',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customcss',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='customcss',
            name='user',
        ),
        migrations.DeleteModel(
            name='DividerAsset',
        ),
        migrations.RemoveField(
            model_name='fontpairing',
            name='theme',
        ),
        migrations.DeleteModel(
            name='IconSet',
        ),
        migrations.DeleteModel(
            name='MusicLibrary',
        ),
        migrations.DeleteModel(
            name='OpeningAnimation',
        ),
        migrations.DeleteModel(
            name='QuoteLibrary',
        ),
        migrations.AlterUniqueTogether(
            name='templatefeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatefeature',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='themecolorpalette',
            name='theme',
        ),
        migrations.AlterUniqueTogether(
            name='themepreview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='themepreview',
            name='theme',
        ),
        migrations.AlterUniqueTogether(
            name='themerating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='themerating',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='themerating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='themesection',
            name='theme',
        ),
        migrations.DeleteModel(
            name='CustomCSS',
        ),
        migrations.DeleteModel(
            name='FontPairing',
        ),
        migrations.DeleteModel(
            name='TemplateFeature',
        ),
        migrations.DeleteModel(
            name='ThemeColorPalette',
        ),
        migrations.DeleteModel(
            name='ThemePreview',
        ),
        migrations.DeleteModel(
            name='ThemeRating',
        ),
        migrations.DeleteModel(
            name='ThemeSection',
        ),
    ]
