# Generated by Django 5.2.8 on 2025-12-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0005_delete_backgroundasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='css_file',
            field=models.CharField(blank=True, help_text="Path relatif file CSS. Contoh: 'minang-01/style.css'", max_length=255, null=True, verbose_name='File CSS Template'),
        ),
        migrations.AddField(
            model_name='theme',
            name='js_file',
            field=models.CharField(blank=True, help_text="Path relatif file JS. Contoh: 'minang-01/script.js'", max_length=255, null=True, verbose_name='File JavaScript Template'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='css_template',
            field=models.TextField(blank=True, verbose_name='CSS Template (Legacy)'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='html_file',
            field=models.CharField(blank=True, help_text="Path relatif file HTML template. Contoh: 'minang-01/index.html'. File disimpan di media/templates_html/{slug}/", max_length=255, null=True, verbose_name='File HTML Template'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='js_template',
            field=models.TextField(blank=True, verbose_name='JavaScript Template (Legacy)'),
        ),
    ]
