# Generated by Django 5.2.8 on 2025-12-17 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0006_theme_css_file_theme_js_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes_data', models.JSONField(default=list, help_text='Array JSON berisi wishes default untuk template', verbose_name='Data Wishes (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_wishes', to='invitation_templates.theme', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Wish Template',
                'verbose_name_plural': 'Wishes Template',
                'ordering': ['-updated_at'],
            },
        ),
    ]
