# Generated by Django 4.2.16 on 2025-12-19 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation_templates', '0007_templatewish'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama Tema')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi Tema')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='public_theme_thumbnails/', verbose_name='Thumbnail')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Mudah'), ('medium', 'Menengah'), ('advanced', 'Lanjutan')], default='easy', max_length=20, verbose_name='Tingkat Kesulitan')),
                ('html_file', models.CharField(blank=True, help_text='Path relatif file HTML template. File disimpan di templates/invitation_templates/public_themes/{slug}/', max_length=255, null=True, verbose_name='File HTML Template')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Harga')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Tema Premium')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Download')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_templates.category', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
            ],
            options={
                'verbose_name': 'Tema Public',
                'verbose_name_plural': 'Tema Public',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tema Editor', 'verbose_name_plural': 'Tema Editor'},
        ),
        migrations.AlterField(
            model_name='templatewish',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_wishes', to='invitation_templates.theme', verbose_name='Template Editor'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='html_file',
            field=models.CharField(blank=True, help_text="Path relatif file HTML template. Contoh: 'minang-01/index.html'. File disimpan di templates/invitation_templates/templates/{slug}/", max_length=255, null=True, verbose_name='File HTML Template'),
        ),
        migrations.CreateModel(
            name='PublicThemeWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes_data', models.JSONField(default=list, help_text='Array JSON berisi wishes default untuk template', verbose_name='Data Wishes (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_theme_wishes', to='invitation_templates.publictheme', verbose_name='Tema Public')),
            ],
            options={
                'verbose_name': 'Wish Tema Public',
                'verbose_name_plural': 'Wishes Tema Public',
                'ordering': ['-updated_at'],
            },
        ),
    ]
