# Generated by Django 4.2.16 on 2025-12-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0008_publictheme_alter_theme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictheme',
            name='html_file',
            field=models.CharField(blank=True, help_text='Path relatif file HTML template. File disimpan di thema/{slug}/', max_length=255, null=True, verbose_name='File HTML Template'),
        ),
    ]
