# Generated by Django 4.2.16 on 2025-12-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_clientprofile_selected_theme_and_more'),
        ('invitation_templates', '0009_alter_publictheme_html_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicthemewish',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='templatewish',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='category',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PublicTheme',
        ),
        migrations.DeleteModel(
            name='PublicThemeWish',
        ),
        migrations.DeleteModel(
            name='TemplateWish',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
